/*
 * This source file was generated by the Gradle 'init' task
 */
package org.llschall.padel;

import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        new Planner().process();
    }
}
