/*
 * This source file was generated by the Gradle 'init' task
 */
package org.llschall.padel;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {
        new Planner().process();
    }
}
